root_dir: /Users/linhao/Desktop/raw_forYY/
output_dir: /Users/linhao/Desktop/raw_forYY/output/
output_fusion_dir: /Users/linhao/Desktop/raw_forYY/output_fusion/
M_detector_cfg: /Users/linhao/eggy_slam/config/rs128.yaml