root_dir: /Users/linhao/Desktop/raw/
output_dir: /Users/linhao/Desktop/raw/output/
output_fusion_dir: /Users/linhao/Desktop/raw/output_fusion/
M_detector_cfg: /Users/linhao/eggy_slam/config/rs128.yaml