dyn_obj:
    dataset: 2 #0 for kitti, 1 for nuscenes, 2 for waymo, 3 for avia
    buffer_delay: 0.1
    buffer_size: 700000
    points_num_perframe: 300000
    depth_map_dur: 0.2

    max_depth_map_num: 10 #10
    max_pixel_points: 5 #5
    frame_dur: 0.1
    self_x_f: 0.5
    self_x_b: -0.5
    self_y_l: 2.2
    self_y_r: -1.0
    blind_dis: 0.3
    #fov parameters
    fov_up: 15.0
    fov_down: -25.0
    # fov_up: 2.4
    # fov_down: -17.6
    
    fov_left: 180.0
    fov_right: -180.0
    fov_cut: 0

    #resolution parameters
    hor_resolution_max: 0.005 # 0.005
    ver_resolution_max: 0.008 # 0.01
    
    #case1 parameters
    depth_thr1: 0.15
    enter_min_thr1: 1.0
    enter_max_thr1: 0.3
    map_cons_depth_thr1: 0.3
    map_cons_hor_thr1: 0.01
    map_cons_ver_thr1: 0.01
    map_cons_hor_dis1: 0.15
    map_cons_ver_dis1: 0.15
    depth_cons_depth_thr1: 0.5
    depth_cons_depth_max_thr1: 1.0
    depth_cons_hor_thr1: 0.01
    depth_cons_ver_thr1: 0.01
    enlarge_z_thr1 : -2.5
    enlarge_angle: 2.0
    enlarge_depth: 3.0
    occluded_map_thr1: 2
    case1_interp_en: true

    #case2 parameters
    v_min_thr2: 0.5
    acc_thr2: 7.0
    map_cons_depth_thr2: 0.2
    map_cons_hor_thr2: 0.01
    map_cons_ver_thr2: 0.01
    occ_depth_thr2: 0.15
    occ_hor_thr2: 0.01
    occ_ver_thr2: 0.01
    depth_cons_depth_thr2: 0.1
    depth_cons_depth_max_thr2: 0.5
    depth_cons_hor_thr2: 0.01
    depth_cons_ver_thr2: 0.01
    occluded_times_thr2: 2
    k_depth2: 0.005
    case2_interp_en: false

    #case3 parameters
    v_min_thr3: 0.5
    acc_thr3: 15.0
    map_cons_depth_thr3: 0.2
    map_cons_hor_thr3: 0.01
    map_cons_ver_thr3: 0.006
    occ_depth_thr3: 0.15
    occ_hor_thr3: 0.01
    occ_ver_thr3: 0.01
    depth_cons_depth_thr3: 0.3
    depth_cons_depth_max_thr3: 1.0
    depth_cons_hor_thr3: 0.01
    depth_cons_ver_thr3: 0.01
    occluding_times_thr3: 2
    k_depth3: 0.005
    case3_interp_en: false

    interp_hor_thr: 0.015
    interp_ver_thr: 0.01
    interp_thr1: 0.5
    interp_static_max: 10010.0
    interp_start_depth1: 10
    interp_kp1: 0.1
    interp_kd1: 0.5
    interp_bg: 0.8
    interp_thr2: 0.25
    interp_thr3: 0.05

    point_index: -1 #71980
    debug_x: 7.2065
    debug_y: -3.1844
    debug_z: -0.89005
    
    #cluster parameters
    cluster_coupled: true
    cluster_future: true
    cluster_extend_pixel: 2 #2
    cluster_min_pixel_number: 3 #3
    cluster_Voxel_revolusion: 0.3 #0.3


    dyn_filter_en: false
    debug_publish: false
    

    